name: orange_school
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.8

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.3
  loading_indicator: ^3.1.1
  dotted_border: ^2.1.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9
  fl_chart: ^0.65.0
  super_tooltip: 2.0.7
  kpostal: ^0.5.1
  remedi_kopo: 0.0.2
  geolocator: ^10.1.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0
  speech_balloon: ^0.0.4
  get: ^4.6.6
  file_picker: ^6.1.1
  simple_shadow: ^0.3.1
  currency_text_input_formatter: ^2.1.8
  url_launcher: 6.2.2
  permission_handler: 11.1.0
  kakao_flutter_sdk_user: ^1.7.0
  path_provider: ^2.1.1
  flutter_naver_login: ^1.8.0
  the_apple_sign_in: ^1.1.1
  firebase_auth: ^4.15.3
  flutter_html: ^3.0.0-beta.2
  xml: ^6.5.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.3.9
  keyboard_actions: ^4.1.0
  firebase_analytics: ^10.8.9
  firebase_app_check: ^0.2.1+17
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Pretendard-Light.ttf
          weight: 300
        - asset: assets/font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/font/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Pretendard-Black.ttf
          weight: 900

    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.ttf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/font/SUIT-Light.ttf
          weight: 300
        - asset: assets/font/SUIT-Regular.ttf
          weight: 400
        - asset: assets/font/SUIT-Medium.ttf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/font/SUIT-Bold.ttf
          weight: 700
        - asset: assets/font/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/font/SUIT-Heavy.ttf
          weight: 900

  assets:
    - assets/config/.env
    - assets/icons/btn_check_off.svg
    - assets/icons/camera.svg
    - assets/icons/btn_check_on.svg
    - assets/icons/btn_check_black.svg
    - assets/icons/naver.svg
    - assets/icons/kakao.svg
    - assets/icons/apple.svg
    - assets/icons/vector.svg
    - assets/icons/close.svg
    - assets/icons/info_green.svg
    - assets/icons/ic_16_clock.svg
    - assets/icons/ic_16_trash.svg
    - assets/icons/ic_24_bell.svg
    - assets/icons/ic_24_color.svg
    - assets/icons/ic_24_profile.svg
    - assets/icons/ic_24_recipe2.svg
    - assets/icons/ic_24_rotate.svg
    - assets/icons/ic_24_story.svg
    - assets/icons/ic_24_money.svg
    - assets/icons/check.svg
    - assets/icons/info_gray.svg
    - assets/icons/challenge_orange.svg
    - assets/icons/challenge_medal.svg
    - assets/icons/challenge_flag_red.svg
    - assets/icons/challenge_flag_green.svg
    - assets/icons/cheer1.png
    - assets/icons/cheer2.png
    - assets/icons/cheer3.png
    - assets/icons/cheer4.png
    - assets/icons/cheer5.png
    - assets/icons/cheer6.png
    - assets/images/check.svg
    - assets/images/login.svg
    - assets/images/splash.png
    - assets/images/sample.png
    - assets/images/challenge.png
    - assets/images/stamp_on.svg
    - assets/images/stamp_off.svg
    - assets/images/orange_on.svg
    - assets/images/orange.svg
    - assets/images/orange_off.svg
    - assets/images/complete.png
    - assets/images/splash_back.svg
    - assets/images/splash_front.svg
    - assets/images/pick.svg
    - assets/icons/alarm.svg
    - assets/icons/alarm_on.svg
    - assets/icons/arrow_right.svg
    - assets/icons/nv_home.svg
    - assets/icons/nv_challenge.svg
    - assets/icons/nv_money.svg
    - assets/icons/nv_post.svg
    - assets/icons/nv_home_on.svg
    - assets/icons/nv_challenge_on.svg
    - assets/icons/nv_money_on.svg
    - assets/icons/nv_post_on.svg
    - assets/icons/new.svg
    - assets/icons/info.svg
    - assets/icons/ic_24_x.svg
    - assets/icons/ic_16_edit.svg
    - assets/icons/ic_16_edit_white.svg
    - assets/icons/profile_1.svg
    - assets/icons/profile_2.svg
    - assets/icons/profile_3.svg
    - assets/images/chart_bg.svg
    - assets/icons/copy.svg
    - assets/icons/check_gray.svg
    - assets/icons/launcher_clear.png
    - assets/icons/ic_all.svg
    - assets/icons/ic_reci.svg
    - assets/icons/ic_moon.svg
    - assets/icons/arrow_right_gray.svg
    - assets/icons/ACADEMY.svg
    - assets/icons/CLASS.svg
    - assets/icons/ETC.svg
    - assets/icons/SCHEDULE.svg
    - assets/icons/SCHOOL.svg
    - assets/icons/VEHICLE.svg
    - assets/icons/ACADEMY_GRAY.svg
    - assets/icons/CLASS_GRAY.svg
    - assets/icons/ETC_GRAY.svg
    - assets/icons/SCHEDULE_GRAY.svg
    - assets/icons/SCHOOL_GRAY.svg
    - assets/icons/VEHICLE_GRAY.svg
    - assets/lines/line1.svg
    - assets/lines/line2.svg
    - assets/lines/line3.svg
    - assets/lines/line4.svg
    - assets/lines/line_slide.svg
    - assets/lines/line_switch.svg
    - assets/lines/x_white.svg
    - assets/lines/line5.svg
    - assets/lines/line6.svg
    - assets/lines/line7.svg
    - assets/lines/line8.svg
    - assets/lines/line9.svg
    - assets/lines/line10.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages